### ISSUE TITLE
Losetup won't bring /dev/loop0p1

### ISSUE THREAD

**Issue by darfpga** [MiSTer-devel/mr-fusion#13] opened 2021-09-17 16:25 UTC
Hi, thanxs for your job.

When using the create-sd-card-image.sh script. Sudo losetup -fP /vagrant/images/mr-fusion.img only brings /dev/loop0p2 device. Device /dev/loop0p1 never appear after ls /dev/lo* (sfdisk shows both partition)

I''am using vagrant file directly from the GitHub except disksize ( commented). My config is virtualbox 5.2.44, vagrant 2.2.18 and box is Ubuntu/bionic64 (18.04.6). Running on Windows 7 sp1 with powershell 3.0.

Can you help me with that problem. I've tried manually many variation of losetup command but never succeed to get the device for the first partition.

**Comment by michaelshmitty** [comment] 2021-09-17 19:05
Hi, thanks for reaching out!

I tried but I cannot reproduce the problem you're having. For the record here is the output I get from the relevant commands in the script. Check if yours give any different output. I've included `lsblk` as well to show the devices / partitions. As you can see on my system it shows both partitions as devices:

```
vagrant@ubuntu-bionic:~$ dd if=/dev/zero of=/vagrant/images/mr-fusion.img bs=12M count=10
10+0 records in
10+0 records out
125829120 bytes (126 MB, 120 MiB) copied, 0.166973 s, 754 MB/s
vagrant@ubuntu-bionic:~$ sfdisk --force /vagrant/images/mr-fusion.img << EOF
> 8192; 241664; 0B
> 2048; 8192; a2
> EOF
Checking that no-one is using this disk right now ... OK

Disk /vagrant/images/mr-fusion.img: 120 MiB, 125829120 bytes, 245760 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

>>> Created a new DOS disklabel with disk identifier 0x354f739c.
/vagrant/images/mr-fusion.img1: Created a new partition 1 of type 'W95 FAT32' and of size 116 MiB.
/vagrant/images/mr-fusion.img2: Created a new partition 2 of type 'Unknown' and of size 3 MiB.
/vagrant/images/mr-fusion.img3: Done.

New situation:
Disklabel type: dos
Disk identifier: 0x354f739c

Device                         Boot Start    End Sectors  Size Id Type
/vagrant/images/mr-fusion.img1       8192 245759  237568  116M  b W95 FAT32
/vagrant/images/mr-fusion.img2       2048   8191    6144    3M a2 unknown

Partition table entries are not in disk order.

The partition table has been altered.
Syncing disks.
vagrant@ubuntu-bionic:~$ lsblk
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sda      8:0    0  50G  0 disk
└─sda1   8:1    0  50G  0 part /
sdb      8:16   0  10M  0 disk
vagrant@ubuntu-bionic:~$ sudo losetup -fP /vagrant/images/mr-fusion.img
vagrant@ubuntu-bionic:~$ lsblk
NAME      MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0       7:0    0  120M  0 loop
├─loop0p1 259:0    0  116M  0 loop
└─loop0p2 259:1    0    3M  0 loop
sda         8:0    0   50G  0 disk
└─sda1      8:1    0   50G  0 part /
sdb         8:16   0   10M  0 disk
vagrant@ubuntu-bionic:~$ sudo dd if="/vagrant/vendor/bootloader.img" of="/dev/loop0p2" bs=64k
32+0 records in
32+0 records out
2097152 bytes (2.1 MB, 2.0 MiB) copied, 0.0218667 s, 95.9 MB/s
vagrant@ubuntu-bionic:~$ sync
vagrant@ubuntu-bionic:~$ sudo mkfs.vfat -n "MRFUSION" /dev/loop0p1
mkfs.fat 4.1 (2017-01-24)
vagrant@ubuntu-bionic:~$ sudo mkdir -p /mnt/data
vagrant@ubuntu-bionic:~$ sudo mount /dev/loop0p1 /mnt/data
vagrant@ubuntu-bionic:~$ sudo umount /mnt/data
vagrant@ubuntu-bionic:~$ sudo losetup -d /dev/loop0
```

Can you share the output of `lsblk` before and after you run the `losetup` command?

My vagrant box shows: Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-124-generic x86_64)
I'm using Vagrant version 2.2.18 with Virtualbox 6.1.26 r145957 on MacOS.
Output of `losetup -V` is `losetup from util-linux 2.31.1`

**Comment by darfpga** [comment] 2021-09-18 12:12
``

**Comment by darfpga** [comment] 2021-09-18 12:46
Thanks for your fast reply. 
Below you can find result of the trial with manual commands and being logged as root under vagrant bionic64.

However I've tried the same thing with Ubuntu on WMare and result is OK.

Back to vagrant I try command with fdisk instead of sfdisk with same bad result.
it's clear that your script is OK and problem is linked to my own configuration between vagrant or virtual box.

I''am surely going to try from fresh new reinstall of vagrant box.

_________________
_________________

PS E:\mr_fusion\mr-fusion-master> vagrant ssh
Welcome to Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-156-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Sat Sep 18 11:15:25 UTC 2021

  System load:  0.03               Processes:             116
  Usage of /:   38.1% of 38.71GB   Users logged in:       0
  Memory usage: 7%                 IP address for enp0s3: 10.0.2.15
  Swap usage:   0%


0 updates can be applied immediately.

Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings


Last login: Fri Sep 17 16:57:34 2021 from 10.0.2.2

//////////////////////////
// TRYING MANUALY AS ROOT
//////////////////////////


root@ubuntu-bionic:/vagrant/images# dd if=/dev/zero of=test.img bs=12M count=10
10+0 records in
10+0 records out
125829120 bytes (126 MB, 120 MiB) copied, 0.816314 s, 154 MB/s

root@ubuntu-bionic:/vagrant/images# sfdisk test.img

Welcome to sfdisk (util-linux 2.31.1).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

Checking that no-one is using this disk right now ... OK

Disk test.img: 120 MiB, 125829120 bytes, 245760 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

sfdisk is going to create a new 'dos' disk label.
Use 'label: <name>' before you define a first partition
to override the default.

Type 'help' to get more information.

>>>
8192; 241664; 0B

Created a new DOS disklabel with disk identifier 0x443838cb.
Created a new partition 1 of type 'W95 FAT32' and of size 116 MiB.
   test.img1 :         8192       245759 (116M) W95 FAT32
test.img2: 2048; 8192; A2
Created a new partition 2 of type 'Unknown' and of size 3 MiB.
   test.img2 :         2048         8191 (3M) unknown
test.img3:
write

New situation:
Disklabel type: dos
Disk identifier: 0x443838cb

Device     Boot Start    End Sectors  Size Id Type
test.img1        8192 245759  237568  116M  b W95 FAT32
test.img2        2048   8191    6144    3M a2 unknown

Partition table entries are not in disk order.

The partition table has been altered.
Syncing disks.

root@ubuntu-bionic:/vagrant/images# lsblk
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sda      8:0    0  40G  0 disk
└─sda1   8:1    0  40G  0 part /
sdb      8:16   0  10M  0 disk

root@ubuntu-bionic:/vagrant/images# losetup -fP test.img

root@ubuntu-bionic:/vagrant/images# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0    7:0    0  120M  1 loop
sda      8:0    0   40G  0 disk
└─sda1   8:1    0   40G  0 part /
sdb      8:16   0   10M  0 disk

root@ubuntu-bionic:/vagrant/images# losetup -a
/dev/loop0: [0049]:20 (/vagrant/images/test.img)

root@ubuntu-bionic:/vagrant/images# losetup -l /dev/loop0
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                DIO LOG-SEC
/dev/loop0         0      0         0  1 /vagrant/images/test.img   0     512


root@ubuntu-bionic:/vagrant/scripts# ll /dev/lo*
lrwxrwxrwx 1 root root      28 Sep 17 16:38 /dev/log -> /run/systemd/journal/dev-log=
crw-rw---- 1 root disk 10, 237 Sep 17 16:38 /dev/loop-control
brw-rw---- 1 root disk  7,   0 Sep 18 12:02 /dev/loop0
brw-rw---- 1 root disk  7,   1 Sep 18 12:01 /dev/loop1
brw-rw---- 1 root disk  7,   2 Sep 17 16:38 /dev/loop2
brw-rw---- 1 root disk  7,   3 Sep 17 16:38 /dev/loop3
brw-rw---- 1 root disk  7,   4 Sep 17 16:38 /dev/loop4
brw-rw---- 1 root disk  7,   5 Sep 17 16:38 /dev/loop5
brw-rw---- 1 root disk  7,   6 Sep 17 16:38 /dev/loop6
brw-rw---- 1 root disk  7,   7 Sep 17 16:38 /dev/loop7

**Comment by michaelshmitty** [comment] 2021-09-18 18:39
Thanks for posting your feedback. Very strange issue!

**Comment by darfpga** [comment] 2021-09-27 20:12
So after many trials and two or three reinstall I finally catch where the problem is.
It seems that the losetup command fails when the target file is on the vagrant host shared directory. I've read somewhere that the vagrant shared directory use a specific mechanism for Windows OS. 

An easy work around is to replace the mr-fusion.img file path from /vagrant/images to /home/vagrant at 3 or 4 place within the create-sd-card script.

**Comment by michaelshmitty** [comment] 2021-09-28 10:53
Good find! Thanks for getting to the bottom of this.
The final image is put in the /vagrant/images folder because that makes it easily accessible from the host system in order to flash it to an SD card.
But I will change the script to construct the image file in /tmp and then copy it to /vagrant/images instead.
Thanks again!

**Comment by michaelshmitty** [comment] 2023-01-23 18:51
Closing this because the project has stopped using Vagrant. Any Linux distro, virtual or on bare metal that can compile Buildroot and the Linux kernel should work.

**Closed by michaelshmitty** 2023-01-23 18:51 UTC
Labels: bug
